// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb8U9XNAPCxhUixjuVzCwycNz-XRJLS40',
    appId: '1:458146971319:web:7215e11400e59068a09732',
    messagingSenderId: '458146971319',
    projectId: 'fruit--hub',
    authDomain: 'fruit--hub.firebaseapp.com',
    storageBucket: 'fruit--hub.firebasestorage.app',
    measurementId: 'G-XTR75FPVF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7dCvanIGQociNmCK9Ro0HGL0G5H0XXnc',
    appId: '1:458146971319:android:f60c1c8dd6bac727a09732',
    messagingSenderId: '458146971319',
    projectId: 'fruit--hub',
    storageBucket: 'fruit--hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_aOOcS6sD_D1kIBJSGNSVAigWacrbKjc',
    appId: '1:458146971319:ios:6bb152c72abb408ca09732',
    messagingSenderId: '458146971319',
    projectId: 'fruit--hub',
    storageBucket: 'fruit--hub.firebasestorage.app',
    androidClientId: '458146971319-sd7avoiipnjhlo2jb2avcqkg3tqol9sr.apps.googleusercontent.com',
    iosClientId: '458146971319-60hb49c1cifbkfaj564pm6jg02s1rkds.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_aOOcS6sD_D1kIBJSGNSVAigWacrbKjc',
    appId: '1:458146971319:ios:6bb152c72abb408ca09732',
    messagingSenderId: '458146971319',
    projectId: 'fruit--hub',
    storageBucket: 'fruit--hub.firebasestorage.app',
    androidClientId: '458146971319-sd7avoiipnjhlo2jb2avcqkg3tqol9sr.apps.googleusercontent.com',
    iosClientId: '458146971319-60hb49c1cifbkfaj564pm6jg02s1rkds.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb8U9XNAPCxhUixjuVzCwycNz-XRJLS40',
    appId: '1:458146971319:web:cd33662fbbc190f8a09732',
    messagingSenderId: '458146971319',
    projectId: 'fruit--hub',
    authDomain: 'fruit--hub.firebaseapp.com',
    storageBucket: 'fruit--hub.firebasestorage.app',
    measurementId: 'G-T9W0M1YRQ0',
  );
}
